export const actionType = {
    UPDATE_COMPANY_ID: 'UPDATE_COMPANY_ID',
    UPDATE_PASS: 'UPDATE_PASS',
    SET_COMPANY_HELPER_TEXT: 'SET_COMPANY_HELPER_TEXT',
    SET_PASS_HELPER_TEXT: 'SET_PASS_HELPER_TEXT',
};
