version: "3"

services:
  db:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
